config/routes.rb
EmoticodeRails::Application.routes.draw do
  root 'home#index'

  namespace :api do
    namespace :v1 do
      resources :languages, :only => [ :index, :show ]
      resources :sources,   :only => [ :index, :show ]
      resources :users,     :only => [ :index, :show ]
    end
  end

  controller :home do
    get 'new'      => :recent,   as: :recent_snippets
    get 'trending' => :trending, as: :trending_snippets
  end

  controller :sitemaps do
    get 'sitemap_index'          => :index,     as: :sitemap_index
    get 'sitemap_snippets-:page' => :snippets,  as: :sitemap_snippets, constraints: { page: Patterns::ID_PATTERN }
    get 'sitemap_languages'      => :languages, as: :sitemap_languages
  end

  controller :sessions do
    get    'sign_in'  => :new,     as: :sign_in
    post   'sign_in'  => :create
    delete 'sign_out' => :destroy, as: :sign_out
  end

  controller :user do
    get  'sign_up'        => :new,     as: :sign_up
    post 'sign_up'        => :create
    get  'confirm/:token' => :confirm, as: :confirm, constraints: { token: Patterns::CONFIRMATION_TOKEN_PATTERN }
  end

  get '/auth/:provider/callback' => 'sessions#create'

  controller :favorite do
    post 'fav/:id'   => :make,    as: :favorite,   constraints: { id: Patterns::ID_PATTERN }
    post 'unfav/:id' => :destroy, as: :unfavorite, constraints: { id: Patterns::ID_PATTERN }
  end

  controller :follows do
    post 'follow/:type/:id'   => :follow,   as: :follow,   constraints: { type: Patterns::ID_PATTERN, id: Patterns::ID_PATTERN }
    post 'unfollow/:type/:id' => :unfollow, as: :unfollow, constraints: { type: Patterns::ID_PATTERN, id: Patterns::ID_PATTERN }    
  end

  controller :profile do
    get   'profile/snippets'    => :snippets,  as: :user_snippets
    get   'profile/favorites'   => :favorites, as: :user_favorites   
    get   'profile/edit'        => :edit, as: :user_settings
    patch 'profile/update'      => :update
    get   'profile/:username'   => :show, as: :user_profile, constraints: { username: Patterns::USERNAME_PATTERN }
    get   'profile/destroy/:id' => :destroy, as: :user_delete, constraints: { id: Patterns::ID_PATTERN }
    get   'profile/ban/:id'     => :ban, as: :user_ban, constraints: { id: Patterns::ID_PATTERN }    
    get   'profile/unban/:id'   => :unban, as: :user_unban, constraints: { id: Patterns::ID_PATTERN }        
    get   'badge/:username'     => :badge, as: :user_badge, constraints: { username: Patterns::USERNAME_PATTERN }
  end

  controller :search do
    get 'search(/:what)' => :search, as: :search, :constraints => {:what => /.*/}
  end

  resource :comments
  resource :votes

  resource :passwords, :only => [:new, :create]
  controller :passwords do
    get  'recovery/:token' => :edit, as: :recovery, constraints: { token: Patterns::CONFIRMATION_TOKEN_PATTERN }
    post 'recovery/:token' => :update, constraints: { token: Patterns::CONFIRMATION_TOKEN_PATTERN }
  end

  controller :feeds do
    get 'feed'                   => :feed,     as: :feed
    get 'feed/:language'         => :language, as: :language_feed, constraints: { language: Patterns::ROUTE_PATTERN }
    get 'profile/:username/feed' => :user,     as: :user_feed, constraints: { username: Patterns::USERNAME_PATTERN }
    get 'randomfeed'             => :random,   as: :random_feed
  end

  controller :page do
    get  'about.html'   => :about,   as: :about_page
    get  'sitemap.html' => :sitemap, as: :sitemap_page
    get  'contact.html' => :contact, as: :contact_page
  end

  controller :language do
    get ':name/',    to: :archive, as: :language_archive, constraints: { name: Patterns::ROUTE_PATTERN }
  end

  controller :source do
    get   'source/new'         => :new,     as: :source_new
    post  'source/create'      => :create,  as: :source_create
    get   'source/edit/:id'    => :edit,    as: :source_edit,   constraints: { id: Patterns::ID_PATTERN }
    get   'source/destroy/:id' => :destroy, as: :source_delete, constraints: { id: Patterns::ID_PATTERN }
    patch 'source/update/:id'  => :update,  as: :source_update, constraints: { id: Patterns::ID_PATTERN }

    get 'source/:id'                       => :show,  as: :source_shortlink,     constraints: { id: Patterns::ID_PATTERN }
    get ':language_name/:source_name.html' => :show,  as: :source_with_language, constraints: { language_name: Patterns::ROUTE_PATTERN, source_name: Patterns::ROUTE_PATTERN }
    get ':language_name/:source_name.txt'  => :raw,   as: :raw_with_language,    constraints: { language_name: Patterns::ROUTE_PATTERN, source_name: Patterns::ROUTE_PATTERN }
    get ':language_name/:source_name.js'   => :embed, as: :embed_with_language,  constraints: { language_name: Patterns::ROUTE_PATTERN, source_name: Patterns::ROUTE_PATTERN }
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  COMMENTABLE_TYPES = {
    :source  => 1,
    :profile => 2
    # more to come :)
  }

  COMMENTABLE_CLASSES = {
    1 => 'Source',
    2 => 'Profile'
  }

  belongs_to :user
  belongs_to :source, -> { where commentable_type: COMMENTABLE_TYPES[:source] }, :foreign_key => :commentable_id

  validates_presence_of  :commentable_id,   :user_id, :content
  validates_inclusion_of :commentable_type, :in => COMMENTABLE_TYPES.values.freeze
  validate               :commentable_exists
  validate               :parent_null_or_exists

  before_save            :parse_content

  # this is needed for nesting comments in ApplicationHelper
  def children
    @children ||= []
    @children
  end

  def commentable
    Kernel.const_get( COMMENTABLE_CLASSES[ commentable_type ] ).find( commentable_id )
  end

  def event_title
    if commentable_type == COMMENTABLE_TYPES[:source]
      Source.find(commentable_id).title
    else commentable_type == COMMENTABLE_TYPES[:profile]
      "#{Profile.find(commentable_id).user.username} profile"
    end
  end

  protected

  include ActionView::Helpers::SanitizeHelper

  def parse_content
    # trim, remove tags and encode entities
    self.content = HTMLEntities.new.encode( self.content.strip )
    # replace newlines with brs and urls with anchors
    self.content = self.content.gsub( /\n/, '<br/>' )
                               .gsub( /(https?:\/\/[A-z0-9~@$%&*_\-\.+\/'=#\?]+)/i, '<a href="\1" target="_blank" rel="nofollow">\1</a>' )
    # replace valid @username with profile links :)
    self.content = self.content.gsub /\@([a-z0-9\-_\.]+)/i do |m|
      m[0] = '' # remove @
      if User.find_by_username( m ).nil?
        "@#{m}"
      else
        "<a href=\"/profile/#{m}\" target=\"_blank\" title=\"#{m} profile\">@#{m}</a>"
      end
    end
  end

  # custom validators

  def commentable_exists
    begin

      commentable

    rescue ActiveRecord::RecordNotFound
      errors.add( :commentable_id, " references to an invalid object ( #{COMMENTABLE_CLASSES[ commentable_type ]} )." )
      false
    end
  end

  def parent_null_or_exists
    begin
      Comment.find( parent_id ) unless parent_id.nil?
    rescue
      errors.add( :commentable_id, " references to an invalid object." )
      false
    end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate!

  def create
    respond_to do |format|
      format.js {
        @comment = Comment.new comment_params
        @comment.user_id = @current_user.id

        if @comment.save
          Event.new_comment(@current_user,@comment)

          if @comment.commentable.user != @current_user
            if @comment.parent_id.nil?
              UserMailer.comment_email( @current_user, @comment.commentable.user, @comment.commentable.url ).deliver
            else
              UserMailer.comment_reply_email( @current_user, @comment.commentable.user, @comment.commentable.url ).deliver
            end
          end
        end
      }
    end
  end

  private

  def comment_params
    params.require(:comment).permit( :parent_id, :commentable_type, :commentable_id, :content )
  end
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/views/comments/_box.html.erb
<%
  heading = 'Comments' if local_assigns[:heading].nil?
%>
<div id="comments" class="headblock">
  <h2><i class="icon-comments"></i> <%= heading %></h2>

  <div class="create">
    <span class="errors"></span>

    <% if signed_in? %>
      <%= form_for @comment, :remote => true do |f| %>
        <%= f.hidden_field :parent_id,        as: :hidden %>
        <%= f.hidden_field :commentable_type, as: :hidden, :value => object.commentable_type %>
        <%= f.hidden_field :commentable_id,   as: :hidden, :value => object.id %>
        <%= f.text_area :content, { :placeholder => 'Leave a message ...' } %>
        <%= f.submit "Comment", :data => { :disable_with => 'Sending ...' }, :class => 'pure-button pure-button-primary' %>
      <% end %>
    <% else %>
      <%= link_to 'Login', sign_in_path %> or <%= link_to 'Register', sign_up_path %> to comment.
    <% end %>
  </div>

  <% if object.comments.empty? == false %>
    <ul class="root">
      <%= render :partial => "comments/listing", :collection => nested_comments(object), :as => 'comment' %>
    </ul>
  <% end %>

  <br style="clear:both"/>
</div>

app/views/comments/_listing.html.erb
<li id="comment-<%= comment.id %>" class="comment">
  <span class="author">
    <a href="<%= user_profile_path(username:comment.user.username) %>" title="<%= comment.user.username %> profile">
      <%= avatar_tag comment.user %>
      <%= truncate comment.user.username, :length => 15 %>
    </a>
  </span>

  <span class="content">
    <%=raw comment.content %>

    <span class="meta">
      <%= time_ago_in_words( Time.at(comment.created_at) ) %> ago &bull; <%= link_icon_to_function 'Reply', 'reply', signed_in? ? "replyToComment( #{comment.id}, '#{comment.user.username}' )" : 'showLoginModal()' %> 
    </span>
    <ul>
    <% comment.children.each do |child| %>
      <%= render :partial => "comments/listing", :locals => { :comment => child } %>
    <% end %>
    </ul>
  </span>
</li>

app/views/comments/create.js.erb
<% if @comment.valid? %>
  window.location.reload();  
<% else %>
  list = '';
  <% @comment.errors.messages.each do |field,errors| %>
    list += '<p class="error"><%= field.to_s.capitalize %> <%= errors[0] %></p>';
  <% end %>

  $('span.errors').html(list);
<% end %>