config/routes.rb
EmoticodeRails::Application.routes.draw do
  root 'home#index'

  namespace :api do
    namespace :v1 do
      resources :languages, :only => [ :index, :show ]
      resources :sources,   :only => [ :index, :show ]
      resources :users,     :only => [ :index, :show ]
    end
  end

  controller :home do
    get 'new'      => :recent,   as: :recent_snippets
    get 'trending' => :trending, as: :trending_snippets
  end

  controller :sitemaps do
    get 'sitemap_index'          => :index,     as: :sitemap_index
    get 'sitemap_snippets-:page' => :snippets,  as: :sitemap_snippets, constraints: { page: Patterns::ID_PATTERN }
    get 'sitemap_languages'      => :languages, as: :sitemap_languages
  end

  controller :sessions do
    get    'sign_in'  => :new,     as: :sign_in
    post   'sign_in'  => :create
    delete 'sign_out' => :destroy, as: :sign_out
  end

  controller :user do
    get  'sign_up'        => :new,     as: :sign_up
    post 'sign_up'        => :create
    get  'confirm/:token' => :confirm, as: :confirm, constraints: { token: Patterns::CONFIRMATION_TOKEN_PATTERN }
  end

  get '/auth/:provider/callback' => 'sessions#create'

  controller :favorite do
    post 'fav/:id'   => :make,    as: :favorite,   constraints: { id: Patterns::ID_PATTERN }
    post 'unfav/:id' => :destroy, as: :unfavorite, constraints: { id: Patterns::ID_PATTERN }
  end

  controller :follows do
    post 'follow/:type/:id'   => :follow,   as: :follow,   constraints: { type: Patterns::ID_PATTERN, id: Patterns::ID_PATTERN }
    post 'unfollow/:type/:id' => :unfollow, as: :unfollow, constraints: { type: Patterns::ID_PATTERN, id: Patterns::ID_PATTERN }    
  end

  controller :profile do
    get   'profile/snippets'    => :snippets,  as: :user_snippets
    get   'profile/favorites'   => :favorites, as: :user_favorites   
    get   'profile/edit'        => :edit, as: :user_settings
    patch 'profile/update'      => :update
    get   'profile/:username'   => :show, as: :user_profile, constraints: { username: Patterns::USERNAME_PATTERN }
    get   'profile/destroy/:id' => :destroy, as: :user_delete, constraints: { id: Patterns::ID_PATTERN }
    get   'profile/ban/:id'     => :ban, as: :user_ban, constraints: { id: Patterns::ID_PATTERN }    
    get   'profile/unban/:id'   => :unban, as: :user_unban, constraints: { id: Patterns::ID_PATTERN }        
    get   'badge/:username'     => :badge, as: :user_badge, constraints: { username: Patterns::USERNAME_PATTERN }
  end

  controller :search do
    get 'search(/:what)' => :search, as: :search, :constraints => {:what => /.*/}
  end

  resource :comments
  resource :votes

  resource :passwords, :only => [:new, :create]
  controller :passwords do
    get  'recovery/:token' => :edit, as: :recovery, constraints: { token: Patterns::CONFIRMATION_TOKEN_PATTERN }
    post 'recovery/:token' => :update, constraints: { token: Patterns::CONFIRMATION_TOKEN_PATTERN }
  end

  controller :feeds do
    get 'feed'                   => :feed,     as: :feed
    get 'feed/:language'         => :language, as: :language_feed, constraints: { language: Patterns::ROUTE_PATTERN }
    get 'profile/:username/feed' => :user,     as: :user_feed, constraints: { username: Patterns::USERNAME_PATTERN }
    get 'randomfeed'             => :random,   as: :random_feed
  end

  controller :page do
    get  'about.html'   => :about,   as: :about_page
    get  'sitemap.html' => :sitemap, as: :sitemap_page
    get  'contact.html' => :contact, as: :contact_page
  end

  controller :language do
    get ':name/',    to: :archive, as: :language_archive, constraints: { name: Patterns::ROUTE_PATTERN }
  end

  controller :source do
    get   'source/new'         => :new,     as: :source_new
    post  'source/create'      => :create,  as: :source_create
    get   'source/edit/:id'    => :edit,    as: :source_edit,   constraints: { id: Patterns::ID_PATTERN }
    get   'source/destroy/:id' => :destroy, as: :source_delete, constraints: { id: Patterns::ID_PATTERN }
    patch 'source/update/:id'  => :update,  as: :source_update, constraints: { id: Patterns::ID_PATTERN }

    get 'source/:id'                       => :show,  as: :source_shortlink,     constraints: { id: Patterns::ID_PATTERN }
    get ':language_name/:source_name.html' => :show,  as: :source_with_language, constraints: { language_name: Patterns::ROUTE_PATTERN, source_name: Patterns::ROUTE_PATTERN }
    get ':language_name/:source_name.txt'  => :raw,   as: :raw_with_language,    constraints: { language_name: Patterns::ROUTE_PATTERN, source_name: Patterns::ROUTE_PATTERN }
    get ':language_name/:source_name.js'   => :embed, as: :embed_with_language,  constraints: { language_name: Patterns::ROUTE_PATTERN, source_name: Patterns::ROUTE_PATTERN }
  end

end

app/views/page/about.html.erb
<section id="page">
  <h1>About</h1>
  <p>
    <strong>EmotiCODE</strong> is a <strong>collaborative</strong> source code snippets aggregator and search engine but mostly a place where developers can find the <strong>answers</strong> they are searching for 
    and contribute with their own contents to <strong>help others</strong> with the same needs.
    <p>
    The main concept behind emoticode is <em>"as a developer i own a lot to people publishing source codes, snippets and guides on the internet, the less i can do is
    do my best to help the internet back"</em>, therefore we encourage people to register ( the process is pretty straightforward ) and post every bit of code they have/use/find on the internet,
    because even the smallest three-line-snippet could solve someone else problems while developing a project ... you never know :)
    </p>
    <p>You can also, as a <strong>registered user</strong>, mark snippets you find more interesting and/or usefull to you as your favorites, clicking on the <i class="icon-thumbs-up"></i> icon on
    the left of every element. This will allow you to find them easily in the future on your profile page and will let other user have an idea on your tastes or specific needs.</p>

    <h3>We <i class="icon-heart"></i> Open Source</h3>

    <p>EmotiCODE itself is an <strong>open source</strong> web application written in <strong>Ruby on Rails</strong>, its source code can be found, forked, patched and pulled on 
    <a href="https://github.com/evilsocket/emoticode" title="EmotiCODE GitHub Repository" target="_blank">GitHub</a>.</p>
    <p>The source code and every component are released under the <a href="https://github.com/evilsocket/emoticode/blob/master/LICENSE.md" title="GPL 3" target="_blank">GPL 3</a> License.</p>

    <h3>Sublime Text Plugin</h3>
    <img src="/sublime.png" style="float:left; width: 110px;margin-top: -10px;margin-left: -5px;margin-right: 10px;">
    <p>
    A Sublime Text plugin has been developed and finally released, you can install it using Package Manager, or manually downloading the files located on <a href="https://github.com/evilsocket/Sublime-Text-2-EmotiCODE-Plugin" title="EmotiCODE Sublime Text Plugin" target="_blank">GitHub</a>.
    </p>
    <p>
    The plugin itself is very similar to StackOverflow one, allowing you to search for custom or selected text on the EmotiCODE search engine for examples and/or snippets.
    For a future release the plugin will be able to post the code under your selection to EmotiCODE itself, using your EmotiCODE account in the configuration.  
    </p>
  </p>
</section>

app/views/page/contact.html.erb
<section id="page">
  <h1>Contact</h1>
  <p>
  To contact us please send an email to 
  <% if signed_in? %>
    <a href="mailto:evilsocket@gmail.com">the admin</a>.
  <% else %>
    <em>- please login or register to see this email address - .</em>
  <% end %>
  </p>
</section>

app/views/page/sitemap.html.erb
<section id="page">
  <h1>Site Map</h1>
  <p>
  We've done our best to make the site look great while keeping it easy to navigate, but sometimes you just wanna get somewhere without all the flashiness. 
  We hope that this page will help you get where you want to go in a hurry.
  </p>

  <h3>Snippets</h3>
  <div class="hkv">
    <div class="k">Contribute</div>
    <div class="v"><%= link_to 'Post a Snippet', source_new_path %></div>
  </div>
  <div class="hkv">
    <div class="k">By Language</div>
    <div class="v">
      <ul>
      <% @languages.each do |lang| %>
        <li>
          <%= link_to lang.title, language_archive_path( :name => lang.name ) %>
        </li>
      <% end %>
      </ul>
    </div>
  </div>

  <h3>Users</h3>
  <div class="hkv">
    <div class="k">Access</div>
    <div class="v">
      <ul>
        <li><%= link_to 'Login',    sign_in_path %>,</li>
        <li><%= link_to 'Register', sign_up_path %></li>
      </ul>  
    </div>
  </div>
  <div class="hkv">
    <div class="k">Connect</div>
    <div class="v">
      <ul>
        <li><%= link_to( 'Facebook', "/auth/facebook", { :title => "Login with your Facebook account." }) %></li>
        <li><%= link_to( 'GitHub', "/auth/github", { :title => "Login with your Github account." }) %></li>
      </ul>  
    </div>
  </div>

  <h3>Pages</h3>
  <div class="hkv">
    <div class="k">List</div>
    <div class="v">
      <ul>
        <% [ 'about', 'contact', 'sitemap' ].each do |page| %>
          <li><a href="/<%= page %>.html" title="<%= page.capitalize %>"><%= page.capitalize %></a></li>
        <% end %>
      </ul>  
    </div>
  </div>
</section>