config/routes.rb
EmoticodeRails::Application.routes.draw do
  root 'home#index'

  namespace :api do
    namespace :v1 do
      resources :languages, :only => [ :index, :show ]
      resources :sources,   :only => [ :index, :show ]
      resources :users,     :only => [ :index, :show ]
    end
  end

  controller :home do
    get 'new'      => :recent,   as: :recent_snippets
    get 'trending' => :trending, as: :trending_snippets
  end

  controller :sitemaps do
    get 'sitemap_index'          => :index,     as: :sitemap_index
    get 'sitemap_snippets-:page' => :snippets,  as: :sitemap_snippets, constraints: { page: Patterns::ID_PATTERN }
    get 'sitemap_languages'      => :languages, as: :sitemap_languages
  end

  controller :sessions do
    get    'sign_in'  => :new,     as: :sign_in
    post   'sign_in'  => :create
    delete 'sign_out' => :destroy, as: :sign_out
  end

  controller :user do
    get  'sign_up'        => :new,     as: :sign_up
    post 'sign_up'        => :create
    get  'confirm/:token' => :confirm, as: :confirm, constraints: { token: Patterns::CONFIRMATION_TOKEN_PATTERN }
  end

  get '/auth/:provider/callback' => 'sessions#create'

  controller :favorite do
    post 'fav/:id'   => :make,    as: :favorite,   constraints: { id: Patterns::ID_PATTERN }
    post 'unfav/:id' => :destroy, as: :unfavorite, constraints: { id: Patterns::ID_PATTERN }
  end

  controller :follows do
    post 'follow/:type/:id'   => :follow,   as: :follow,   constraints: { type: Patterns::ID_PATTERN, id: Patterns::ID_PATTERN }
    post 'unfollow/:type/:id' => :unfollow, as: :unfollow, constraints: { type: Patterns::ID_PATTERN, id: Patterns::ID_PATTERN }    
  end

  controller :profile do
    get   'profile/snippets'    => :snippets,  as: :user_snippets
    get   'profile/favorites'   => :favorites, as: :user_favorites   
    get   'profile/edit'        => :edit, as: :user_settings
    patch 'profile/update'      => :update
    get   'profile/:username'   => :show, as: :user_profile, constraints: { username: Patterns::USERNAME_PATTERN }
    get   'profile/destroy/:id' => :destroy, as: :user_delete, constraints: { id: Patterns::ID_PATTERN }
    get   'profile/ban/:id'     => :ban, as: :user_ban, constraints: { id: Patterns::ID_PATTERN }    
    get   'profile/unban/:id'   => :unban, as: :user_unban, constraints: { id: Patterns::ID_PATTERN }        
    get   'badge/:username'     => :badge, as: :user_badge, constraints: { username: Patterns::USERNAME_PATTERN }
  end

  controller :search do
    get 'search(/:what)' => :search, as: :search, :constraints => {:what => /.*/}
  end

  resource :comments
  resource :votes

  resource :passwords, :only => [:new, :create]
  controller :passwords do
    get  'recovery/:token' => :edit, as: :recovery, constraints: { token: Patterns::CONFIRMATION_TOKEN_PATTERN }
    post 'recovery/:token' => :update, constraints: { token: Patterns::CONFIRMATION_TOKEN_PATTERN }
  end

  controller :feeds do
    get 'feed'                   => :feed,     as: :feed
    get 'feed/:language'         => :language, as: :language_feed, constraints: { language: Patterns::ROUTE_PATTERN }
    get 'profile/:username/feed' => :user,     as: :user_feed, constraints: { username: Patterns::USERNAME_PATTERN }
    get 'randomfeed'             => :random,   as: :random_feed
  end

  controller :page do
    get  'about.html'   => :about,   as: :about_page
    get  'sitemap.html' => :sitemap, as: :sitemap_page
    get  'contact.html' => :contact, as: :contact_page
  end

  controller :language do
    get ':name/',    to: :archive, as: :language_archive, constraints: { name: Patterns::ROUTE_PATTERN }
  end

  controller :source do
    get   'source/new'         => :new,     as: :source_new
    post  'source/create'      => :create,  as: :source_create
    get   'source/edit/:id'    => :edit,    as: :source_edit,   constraints: { id: Patterns::ID_PATTERN }
    get   'source/destroy/:id' => :destroy, as: :source_delete, constraints: { id: Patterns::ID_PATTERN }
    patch 'source/update/:id'  => :update,  as: :source_update, constraints: { id: Patterns::ID_PATTERN }

    get 'source/:id'                       => :show,  as: :source_shortlink,     constraints: { id: Patterns::ID_PATTERN }
    get ':language_name/:source_name.html' => :show,  as: :source_with_language, constraints: { language_name: Patterns::ROUTE_PATTERN, source_name: Patterns::ROUTE_PATTERN }
    get ':language_name/:source_name.txt'  => :raw,   as: :raw_with_language,    constraints: { language_name: Patterns::ROUTE_PATTERN, source_name: Patterns::ROUTE_PATTERN }
    get ':language_name/:source_name.js'   => :embed, as: :embed_with_language,  constraints: { language_name: Patterns::ROUTE_PATTERN, source_name: Patterns::ROUTE_PATTERN }
  end

end

app/models/language.rb
class Language < ActiveRecord::Base
  has_many :sources
  has_many :tags, :through => :links

  scope :popular, -> { order('sources_count DESC') }

  def most_active_users( limit = 3 )
    Rails.cache.fetch "stats_of_#{limit}_users_for_language_#{id}", :expires_in => 24.hours do 
      User.
        joins(:sources).
        select('users.*, COUNT(sources.id) AS hits').
        where( 'sources.language_id = ?', id ).
        where( 'sources.private = 0' ).
        where( 'users.is_bot = 0' ).
        group('users.id').
        order('COUNT(sources.id) DESC').
        limit( limit ).
        to_a
    end
  end
end

app/models/legacy/language.rb
module Legacy
  class Language < Legacy::Base
    belongs_to :source, :class_name => 'Legacy::Source', :foreign_key => 'language_id'
  end
end

app/controllers/api/v1/languages_controller.rb
class Api::V1::LanguagesController < Api::V1::ApiController
  def index
    @languages = Language.all 
  end

  def show
    @language = Language.find_by_name params[:id]
    @per_page = 15
    @sources  = @language.sources.public.paginate( :page => params[:page], :per_page => @per_page )
  end
end

app/controllers/language_controller.rb
class LanguageController < ApplicationController
  def archive
    @language = Language.find_by_name params[:name]
    if @language
      @sources = @language.sources.public.paginate( :page => params[:page], :per_page => 16 )
      @podium  = @language.most_active_users
      @cloud   = Tag.cloud(@language).shuffle!
    else
      render_404 
    end
  end
end

app/helpers/language_helper.rb
module LanguageHelper
  include SeoHelper

  def page_title
    paged "#{@language.title} Snippets | emoticode"
  end

  def metas
    make_seo do |seo|
      seo.description = paged seo.language.description % Array.new( 2, @language.title ) 
      seo.keywords    = seo.language.keywords % Array.new( 5, @language.title )
    end
  end
end

app/views/language/archive.html.erb
<section id="language-archive">
  <div class="huge-column">
    <div class="headblock">
      <h1>
        <%= link_to image_tag('icons/rss-s.png'), language_feed_path(:language => @language.name ), :title => "#{@language.title} RSS feed." %>
        <%= paged "#{@language.title} Snippets Archive" %>
      </h1>

      <%= render :partial => "follows/follow", :locals => { :type => :language, :object => @language, :clazz => 'followlang' }%>       

      <% if @podium and @podium.count > 0 %>
        <%
          first, second, third = @podium
          @podium = { :second => [ second, 2 ], :first => [ first, 1 ], :third => [ third, 3 ] }
        %>
        <div id="podium">
          <h3>Most Active Users</h3>
          <% @podium.each do |position,(user,number)| %>
            <div class="bar <%= position %>">
            <% if user %>
            <div class="user">
              <a href="<%= user_profile_path(username:user.username) %>" title="<%= user.username %> profile">
                <%= avatar_tag user %>
                <%= truncate user.username, :length => 15 %>
              </a>              
            </div>
            <% end %>
            <span><%= number %></span>
          </div>
          <% end %>
        </div>
      <% end %>
    </div>

    <center>
      <%= adsense :slot => '9597895776', :width => 728, :height => 90 %>
    </center>

    <ul class="listing">
      <%= render :partial => "source/listing", :collection => @sources, :as => 'source' %>
    </ul>
  </div>

  <%= render :partial => 'layouts/sidebar', :locals => { with_heading: true } %>
</section>

<br style="clear:both"/>

<section class="pager">
  <%= will_paginate @sources %>
</section>